export const ActionTypes = {
    REQUEST_DATA: 'REQUEST_DATA',
    REQUEST_SUCCESSFULL : 'REQUEST_SUCCESSFULL',
    REQUEST_FAILED: 'REQUEST_FAILED',
    REQUEST_CITY: 'REQUEST_CITY',
    COORDINATES: 'COORDINATES'
}